# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHUJzrl4DvMUqjkE0q_XR0Uesi2FDmx9
"""

# Simple program for addition

# Input two numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Perform addition
result = num1 + num2

# Display the result
print(f"The sum of {num1} and {num2} is: {result}")